"""
train.py

Trains a YOLOv8 model on the fire/smoke dataset described by
training/data.yaml (generated by prepare_data.py).

Usage:
    python training/train.py
    python training/train.py --model yolov8s.pt --epochs 150 --batch 32
"""
import argparse
from pathlib import Path

from ultralytics import YOLO


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default=str(Path(__file__).parent / "data.yaml"))
    parser.add_argument("--model", default="yolov8n.pt",
                         help="base checkpoint to fine-tune: yolov8n/s/m/l/x.pt "
                              "(n = fastest/smallest, x = most accurate/slowest)")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default="0", help="'0' for first CUDA GPU, 'cpu' for CPU")
    parser.add_argument("--name", default="fire_smoke_yolov8")
    parser.add_argument("--patience", type=int, default=30, help="early stopping patience (epochs)")
    args = parser.parse_args()

    if not Path(args.data).exists():
        raise SystemExit(f"{args.data} not found. Run 'python training/prepare_data.py' first.")

    model = YOLO(args.model)

    model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        name=args.name,
        patience=args.patience,
        project="training/runs",
    )
    # Best weights end up at: training/runs/<name>/weights/best.pt


if __name__ == "__main__":
    main()
